### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by DhanushS212003** [fssa-batch3/vigneshwar.vijayakumar__web_project#11]
### Description of issue
On the shop page, the header displays the sign in and sign up links after successfully signing in to the website. Also, on the shop page, the back to home link redirects to the home page, and the header displays the sign in and sign up links.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/shop/shop.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--global-fun-city.netlify.app%2Fpages%2Fshop%2Fshop.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--global-fun-city.netlify.app/pages/shop/shop.html)

**Comment by vigneshwarvj** [comment]
As per your request, I fixed this issue.

**Comment by DhanushS212003** [comment]
Thank you for solving the issue. I have checked it.
