### ISSUE TITLE
DOB limit

### ISSUE THREAD

**Issue by DhanushS212003** [fssa-batch3/vigneshwar.vijayakumar__web_project#4]
### Description of issue
DOB exceeds the limit of today's date

### Expected result
It has to show up by today's date.

### Actual result
It shows beyond today's date.

### Steps to reproduce
1. Set the limit to date
2. 
3. 

```
Path:      /pages/signup%20for%20booking/create-an-account.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--global-fun-city.netlify.app%2Fpages%2Fsignup%2520for%2520booking%2Fcreate-an-account.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--global-fun-city.netlify.app/pages/signup%20for%20booking/create-an-account.html)

**Comment by vigneshwarvj** [comment]
In my website, DOB field is not required. So, I removed.

**Comment by DhanushS212003** [comment]
Thank you for solving the issue. I have checked it.
