### ISSUE TITLE
Forcing the user to receive updates from the website.

### ISSUE THREAD

**Issue by DhanushS212003** [fssa-batch3/vigneshwar.vijayakumar__web_project#5]
### Description of issue
Compels the user to check the checkbox on the registration page for the website's updates.

### Expected result
The checkbox field has to be optional.

### Actual result
The checkbox field is mandatory.

### Steps to reproduce
1. Remove the required attribute from the checkbox input tag.
2. 
3. 

```
Path:      /pages/signup%20for%20booking/create-an-account.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--global-fun-city.netlify.app%2Fpages%2Fsignup%2520for%2520booking%2Fcreate-an-account.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--global-fun-city.netlify.app/pages/signup%20for%20booking/create-an-account.html)

**Comment by vigneshwarvj** [comment]
As your request, I fixed issue in my website.

**Comment by DhanushS212003** [comment]
Thank you for solving the issue. I have tested it, and it's working perfectly.
