### ISSUE TITLE
Don't save the input in the country field.

### ISSUE THREAD

**Issue by DhanushS212003** [fssa-batch3/vigneshwar.vijayakumar__web_project#7]
### Description of issue
On the profile page, the country field doesn't save the input.

### Expected result
It has to save.

### Actual result
It doesn't save.

### Steps to reproduce
1. Save the input in the local storage.
2. 
3. 

```
Path:      /pages/homepage/profile.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--global-fun-city.netlify.app%2Fpages%2Fhomepage%2Fprofile.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--global-fun-city.netlify.app/pages/homepage/profile.html)

**Comment by vigneshwarvj** [comment]
I already get the value from shopGlobal. I need not to store again.

**Comment by DhanushS212003** [comment]
Thank you for solving the issue. I have checked it.
