### ISSUE TITLE
Wishlist page issue

### ISSUE THREAD

**Issue by DhanushS212003** [fssa-batch3/vigneshwar.vijayakumar__web_project#9]
### Description of issue
On the shop page, the wishlist link is not redirecting to the wishlist page.

### Expected result
It has to be redirected to the wishlist page.

### Actual result
It shows an empty page.

### Steps to reproduce
1. Make sure that the URL is correct.
2. 
3. 

```
Path:      /index.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--global-fun-city.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--global-fun-city.netlify.app/index.html)

**Comment by vigneshwarvj** [comment]
I didn't mentioned wishlist (completed) in a readme file. Please take 5 mins to read readme file.
